# GitHub Sponsor and Donation configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Dismonder]
ko_fi: dismonder
custom:
  - https://buycoffee.to/dismonder
  - https://patronite.pl/Dismonder
